# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'B-umiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for B-umiOS
  pod 'Alamofire', '~> 5.4'
  pod 'Then'
  pod 'SnapKit', '~> 5.0.0'
  pod 'lottie-ios'
  pod 'MultiProgressView'

end
